name: Deploy to server

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [closed]

jobs:
  pull_if_merged:
    #if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          git checkout main
          git pull
